name: continuous-integration

on:
  push:
    branches:
    - master
    - release*
    tags:
    - v1.*
    - v2.*
  pull_request:
    branches:
    - master
    - release*

env:
  E2E_SETUP_KIND: yes
  E2E_SETUP_KUBECTL: yes
  SUDO: sudo

jobs:
  ci-go-lint:
    name: ci-go-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install

    - name: Lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
        make lint

  ci-validate-go-modules:
    name: ci-validate-go-modules
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install

    - name: Validate vendor is in sync with go modules
      run: |
        make validate-modules

  ci-unit-tests:
    name: ci-unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install

    - name: Unit tests
      run: |
        make test
